<?php

namespace Mediadata\Utils;


class UTF8ToAsciiMap
{

    public const MAP = [
        'À' => 'A',
        'Á' => 'A',
        'Â' => 'A',
        'Ã' => 'A',
        'Ä' => 'A',
        'Å' => 'A',
        'Æ' => 'A',
        'Ç' => 'C',
        'È' => 'E',
        'É' => 'E',
        'Ê' => 'E',
        'Ë' => 'E',
        'Ì' => 'I',
        'Í' => 'I',
        'Î' => 'I',
        'Ï' => 'I',
        'Ð' => 'D',
        'Ñ' => 'N',
        'Ò' => 'O',
        'Ó' => 'O',
        'Ô' => 'O',
        'Õ' => 'O',
        'Ö' => 'O',
        'Ő' => 'O',
        'Ø' => 'O',
        'Ù' => 'U',
        'Ú' => 'U',
        'Û' => 'U',
        'Ü' => 'U',
        'Ű' => 'U',
        'Ý' => 'Y',
        'Þ' => 'b',
        'ß' => 's',
        'à' => 'a',
        'á' => 'a',
        'â' => 'a',
        'ã' => 'a',
        'ä' => 'a',
        'å' => 'a',
        'æ' => 'a',
        'ç' => 'c',
        'è' => 'e',
        'é' => 'e',
        'ê' => 'e',
        'ë' => 'e',
        'ì' => 'i',
        'í' => 'i',
        'î' => 'i',
        'ï' => 'i',
        'ð' => 'd',
        'ñ' => 'n',
        'ò' => 'o',
        'ó' => 'o',
        'ô' => 'o',
        'õ' => 'o',
        'ö' => 'o',
        'ő' => 'o',
        'ø' => 'o',
        'ù' => 'u',
        'ú' => 'u',
        'û' => 'u',
        'ű' => 'u',
        'ü' => 'u',
        'ý' => 'y',
        'þ' => 'b',
        'ÿ' => 'y',
        'Ā' => 'A', //	c4 80	LATIN CAPITAL LETTER A WITH MACRON
        'ā' => 'a',//	c4 81	LATIN SMALL LETTER A WITH MACRON
        'Ă' => 'A',//	c4 82	LATIN CAPITAL LETTER A WITH BREVE
        'ă' => 'a',//	c4 83	LATIN SMALL LETTER A WITH BREVE
        'Ą' => 'A',//	c4 84	LATIN CAPITAL LETTER A WITH OGONEK
        'ą' => 'a',//	c4 85	LATIN SMALL LETTER A WITH OGONEK
        'Ć' => 'C',//	c4 86	LATIN CAPITAL LETTER C WITH ACUTE
        'ć' => 'c',//	c4 87	LATIN SMALL LETTER C WITH ACUTE
        'Ĉ' => 'C',//	c4 88	LATIN CAPITAL LETTER C WITH CIRCUMFLEX
        'ĉ' => 'c',//	c4 89	LATIN SMALL LETTER C WITH CIRCUMFLEX
        'Ċ' => 'C',//	c4 8a	LATIN CAPITAL LETTER C WITH DOT ABOVE
        'ċ' => 'c',//	c4 8b	LATIN SMALL LETTER C WITH DOT ABOVE
        'Č' => 'C',//	c4 8c	LATIN CAPITAL LETTER C WITH CARON
        'č' => 'c',//	c4 8d	LATIN SMALL LETTER C WITH CARON
        'Ď' => 'D',//	c4 8e	LATIN CAPITAL LETTER D WITH CARON
        'ď' => 'd',//	c4 8f	LATIN SMALL LETTER D WITH CARON
        'Đ' => 'D',//	c4 90	LATIN CAPITAL LETTER D WITH STROKE
        'đ' => 'd',//	c4 91	LATIN SMALL LETTER D WITH STROKE
        'Ē' => 'E',//	c4 92	LATIN CAPITAL LETTER E WITH MACRON
        'ē' => 'e',//	c4 93	LATIN SMALL LETTER E WITH MACRON
        'Ĕ' => 'E',//	c4 94	LATIN CAPITAL LETTER E WITH BREVE
        'ĕ' => 'e',//	c4 95	LATIN SMALL LETTER E WITH BREVE
        'Ė' => 'E',//	c4 96	LATIN CAPITAL LETTER E WITH DOT ABOVE
        'ė' => 'e',//	c4 97	LATIN SMALL LETTER E WITH DOT ABOVE
        'Ę' => 'E',//	c4 98	LATIN CAPITAL LETTER E WITH OGONEK
        'ę' => 'e',//	c4 99	LATIN SMALL LETTER E WITH OGONEK
        'Ě' => 'E',//	c4 9a	LATIN CAPITAL LETTER E WITH CARON
        'ě' => 'e',//	c4 9b	LATIN SMALL LETTER E WITH CARON
        'Ĝ' => 'G',//	c4 9c	LATIN CAPITAL LETTER G WITH CIRCUMFLEX
        'ĝ' => 'g',//	c4 9d	LATIN SMALL LETTER G WITH CIRCUMFLEX
        'Ğ' => 'G',//	c4 9e	LATIN CAPITAL LETTER G WITH BREVE
        'ğ' => 'g',//	c4 9f	LATIN SMALL LETTER G WITH BREVE
        'Ġ' => 'G',//	c4 a0	LATIN CAPITAL LETTER G WITH DOT ABOVE
        'ġ' => 'g',//	c4 a1	LATIN SMALL LETTER G WITH DOT ABOVE
        'Ģ' => 'G',//	c4 a2	LATIN CAPITAL LETTER G WITH CEDILLA
        'ģ' => 'g',//	c4 a3	LATIN SMALL LETTER G WITH CEDILLA
        'Ĥ' => 'H',//	c4 a4	LATIN CAPITAL LETTER H WITH CIRCUMFLEX
        'ĥ' => 'h',//	c4 a5	LATIN SMALL LETTER H WITH CIRCUMFLEX
        'Ħ' => 'H',//	c4 a6	LATIN CAPITAL LETTER H WITH STROKE
        'ħ' => 'h',//	c4 a7	LATIN SMALL LETTER H WITH STROKE
        'Ĩ' => 'I',//	c4 a8	LATIN CAPITAL LETTER I WITH TILDE
        'ĩ' => 'i',//	c4 a9	LATIN SMALL LETTER I WITH TILDE
        'Ī' => 'I',//	c4 aa	LATIN CAPITAL LETTER I WITH MACRON
        'ī' => 'i',//	c4 ab	LATIN SMALL LETTER I WITH MACRON
        'Ĭ' => 'I',//	c4 ac	LATIN CAPITAL LETTER I WITH BREVE
        'ĭ' => 'i',//	c4 ad	LATIN SMALL LETTER I WITH BREVE
        'Į' => 'I',//	c4 ae	LATIN CAPITAL LETTER I WITH OGONEK
        'į' => 'i',//	c4 af	LATIN SMALL LETTER I WITH OGONEK
        'İ' => 'I',//	c4 b0	LATIN CAPITAL LETTER I WITH DOT ABOVE
        'ı' => 'i',//	c4 b1	LATIN SMALL LETTER DOTLESS I
        'Ĳ' => 'IJ',//	c4 b2	LATIN CAPITAL LIGATURE IJ
        'ĳ' => 'ij',//	c4 b3	LATIN SMALL LIGATURE IJ
        'Ĵ' => 'J',//	c4 b4	LATIN CAPITAL LETTER J WITH CIRCUMFLEX
        'ĵ' => 'j',//	c4 b5	LATIN SMALL LETTER J WITH CIRCUMFLEX
        'Ķ' => 'K',//	c4 b6	LATIN CAPITAL LETTER K WITH CEDILLA
        'ķ' => 'k',//	c4 b7	LATIN SMALL LETTER K WITH CEDILLA
        'ĸ' => 'k',//	c4 b8	LATIN SMALL LETTER KRA
        'Ĺ' => 'L',//	c4 b9	LATIN CAPITAL LETTER L WITH ACUTE
        'ĺ' => 'l',//	c4 ba	LATIN SMALL LETTER L WITH ACUTE
        'Ļ' => 'L',//	c4 bb	LATIN CAPITAL LETTER L WITH CEDILLA
        'ļ' => 'l',//	c4 bc	LATIN SMALL LETTER L WITH CEDILLA
        'Ľ' => 'L',//	c4 bd	LATIN CAPITAL LETTER L WITH CARON
        'ľ' => 'l',//	c4 be	LATIN SMALL LETTER L WITH CARON
        'Ŀ' => 'L',//	c4 bf	LATIN CAPITAL LETTER L WITH MIDDLE DOT
        'ŀ' => 'l',//	c5 80	LATIN SMALL LETTER L WITH MIDDLE DOT
        'Ł' => 'L',//	c5 81	LATIN CAPITAL LETTER L WITH STROKE
        'ł' => 'l',//	c5 82	LATIN SMALL LETTER L WITH STROKE
        'Ń' => 'N',//	c5 83	LATIN CAPITAL LETTER N WITH ACUTE
        'ń' => 'n',//	c5 84	LATIN SMALL LETTER N WITH ACUTE
        'Ņ' => 'N',//	c5 85	LATIN CAPITAL LETTER N WITH CEDILLA
        'ņ' => 'n',//	c5 86	LATIN SMALL LETTER N WITH CEDILLA
        'Ň' => 'N',//	c5 87	LATIN CAPITAL LETTER N WITH CARON
        'ň' => 'n',//	c5 88	LATIN SMALL LETTER N WITH CARON
        'ŉ' => 'n',//	c5 89	LATIN SMALL LETTER N PRECEDED BY APOSTROPHE
        'Ŋ' => 'N',//	c5 8a	LATIN CAPITAL LETTER ENG
        'ŋ' => 'n',//	c5 8b	LATIN SMALL LETTER ENG
        'Ō' => 'O',//	c5 8c	LATIN CAPITAL LETTER O WITH MACRON
        'ō' => 'o',//	c5 8d	LATIN SMALL LETTER O WITH MACRON
        'Ŏ' => 'O',//	c5 8e	LATIN CAPITAL LETTER O WITH BREVE
        'ŏ' => 'o',//	c5 8f	LATIN SMALL LETTER O WITH BREVE
        'Œ' => 'OE',//	c5 92	LATIN CAPITAL LIGATURE OE
        'œ' => 'oe',//	c5 93	LATIN SMALL LIGATURE OE
        'Ŕ' => 'R',//	c5 94	LATIN CAPITAL LETTER R WITH ACUTE
        'ŕ' => 'r',//	c5 95	LATIN SMALL LETTER R WITH ACUTE
        'Ŗ' => 'R',//	c5 96	LATIN CAPITAL LETTER R WITH CEDILLA
        'ŗ' => 'r',//	c5 97	LATIN SMALL LETTER R WITH CEDILLA
        'Ř' => 'R',//	c5 98	LATIN CAPITAL LETTER R WITH CARON
        'ř' => 'r',//	c5 99	LATIN SMALL LETTER R WITH CARON
        'Ś' => 'S',//	c5 9a	LATIN CAPITAL LETTER S WITH ACUTE
        'ś' => 's',//	c5 9b	LATIN SMALL LETTER S WITH ACUTE
        'Ŝ' => 'S',//	c5 9c	LATIN CAPITAL LETTER S WITH CIRCUMFLEX
        'ŝ' => 's',//	c5 9d	LATIN SMALL LETTER S WITH CIRCUMFLEX
        'Ş' => 'S',//	c5 9e	LATIN CAPITAL LETTER S WITH CEDILLA
        'ş' => 's',//	c5 9f	LATIN SMALL LETTER S WITH CEDILLA
        'Š' => 'S',//	c5 a0	LATIN CAPITAL LETTER S WITH CARON
        'š' => 's',//	c5 a1	LATIN SMALL LETTER S WITH CARON
        'Ţ' => 'T',//	c5 a2	LATIN CAPITAL LETTER T WITH CEDILLA
        'ţ' => 't',//	c5 a3	LATIN SMALL LETTER T WITH CEDILLA
        'Ť' => 'T',//	c5 a4	LATIN CAPITAL LETTER T WITH CARON
        'ť' => 't',//	c5 a5	LATIN SMALL LETTER T WITH CARON
        'Ŧ' => 'T',//	c5 a6	LATIN CAPITAL LETTER T WITH STROKE
        'ŧ' => 't',//	c5 a7	LATIN SMALL LETTER T WITH STROKE
        'Ũ' => 'U',//	c5 a8	LATIN CAPITAL LETTER U WITH TILDE
        'ũ' => 'u',//	c5 a9	LATIN SMALL LETTER U WITH TILDE
        'Ū' => 'U',//	c5 aa	LATIN CAPITAL LETTER U WITH MACRON
        'ū' => 'u',//	c5 ab	LATIN SMALL LETTER U WITH MACRON
        'Ŭ' => 'U',//	c5 ac	LATIN CAPITAL LETTER U WITH BREVE
        'ŭ' => 'u',//	c5 ad	LATIN SMALL LETTER U WITH BREVE
        'Ů' => 'U',//	c5 ae	LATIN CAPITAL LETTER U WITH RING ABOVE
        'ů' => 'u',//	c5 af	LATIN SMALL LETTER U WITH RING ABOVE
        'Ų' => 'U',//	c5 b2	LATIN CAPITAL LETTER U WITH OGONEK
        'ų' => 'u',//	c5 b3	LATIN SMALL LETTER U WITH OGONEK
        'Ŵ' => 'W',//	c5 b4	LATIN CAPITAL LETTER W WITH CIRCUMFLEX
        'ŵ' => 'w',//	c5 b5	LATIN SMALL LETTER W WITH CIRCUMFLEX
        'Ŷ' => 'Y',//	c5 b6	LATIN CAPITAL LETTER Y WITH CIRCUMFLEX
        'ŷ' => 'y',//	c5 b7	LATIN SMALL LETTER Y WITH CIRCUMFLEX
        'Ÿ' => 'Y',//	c5 b8	LATIN CAPITAL LETTER Y WITH DIAERESIS
        'Ź' => 'Z',//	c5 b9	LATIN CAPITAL LETTER Z WITH ACUTE
        'ź' => 'z',//	c5 ba	LATIN SMALL LETTER Z WITH ACUTE
        'Ż' => 'Z',//	c5 bb	LATIN CAPITAL LETTER Z WITH DOT ABOVE
        'ż' => 'z',//	c5 bc	LATIN SMALL LETTER Z WITH DOT ABOVE
        'Ž' => 'Z',//	c5 bd	LATIN CAPITAL LETTER Z WITH CARON
        'ž' => 'z',//	c5 be	LATIN SMALL LETTER Z WITH CARON
        'ſ' => 's',//	c5 bf	LATIN SMALL LETTER LONG S
        'ƀ' => 'b',//	c6 80	LATIN SMALL LETTER B WITH STROKE
        'Ɓ' => 'B',//	c6 81	LATIN CAPITAL LETTER B WITH HOOK
        'Ƃ' => 'B',//	c6 82	LATIN CAPITAL LETTER B WITH TOPBAR
        'ƃ' => 'b',//	c6 83	LATIN SMALL LETTER B WITH TOPBAR
        'Ƅ' => 'B',//	c6 84	LATIN CAPITAL LETTER TONE SIX
        'ƅ' => 'b',//	c6 85	LATIN SMALL LETTER TONE SIX
        'Ɔ' => 'O',//	c6 86	LATIN CAPITAL LETTER OPEN O
        'Ƈ' => 'C',//	c6 87	LATIN CAPITAL LETTER C WITH HOOK
        'ƈ' => 'c',//	c6 88	LATIN SMALL LETTER C WITH HOOK
        'Ɖ' => 'D',//	c6 89	LATIN CAPITAL LETTER AFRICAN D
        'Ɗ' => 'D',//	c6 8a	LATIN CAPITAL LETTER D WITH HOOK
        'Ƌ' => 'D',//	c6 8b	LATIN CAPITAL LETTER D WITH TOPBAR
        'ƌ' => 'd',//	c6 8c	LATIN SMALL LETTER D WITH TOPBAR
        'ƍ' => 'd',//	c6 8d	LATIN SMALL LETTER TURNED DELTA
        'Ǝ' => 'E',//	c6 8e	LATIN CAPITAL LETTER REVERSED E
        'Ə' => 'S',//	c6 8f	LATIN CAPITAL LETTER SCHWA
        'Ɛ' => 'E',//	c6 90	LATIN CAPITAL LETTER OPEN E
        'Ƒ' => 'F',//	c6 91	LATIN CAPITAL LETTER F WITH HOOK
        'ƒ' => 'f',//	c6 92	LATIN SMALL LETTER F WITH HOOK
        'Ɠ' => 'G',//	c6 93	LATIN CAPITAL LETTER G WITH HOOK
        'Ɣ' => 'G',//	c6 94	LATIN CAPITAL LETTER GAMMA
        'ƕ' => 'hv',//	c6 95	LATIN SMALL LETTER HV
        'Ɩ' => 'I',//	c6 96	LATIN CAPITAL LETTER IOTA
        'Ɨ' => 'I',//	c6 97	LATIN CAPITAL LETTER I WITH STROKE
        'Ƙ' => 'K',//	c6 98	LATIN CAPITAL LETTER K WITH HOOK
        'ƙ' => 'k',//	c6 99	LATIN SMALL LETTER K WITH HOOK
        'ƚ' => 'l',//	c6 9a	LATIN SMALL LETTER L WITH BAR
        'ƛ' => 'l',//	c6 9b	LATIN SMALL LETTER LAMBDA WITH STROKE
        'Ɯ' => 'M',//	c6 9c	LATIN CAPITAL LETTER TURNED M
        'Ɲ' => 'N',//	c6 9d	LATIN CAPITAL LETTER N WITH LEFT HOOK
        'ƞ' => 'n',//	c6 9e	LATIN SMALL LETTER N WITH LONG RIGHT LEG
        'Ɵ' => 'O',//	c6 9f	LATIN CAPITAL LETTER O WITH MIDDLE TILDE
        'Ơ' => 'O',//	c6 a0	LATIN CAPITAL LETTER O WITH HORN
        'ơ' => 'O',//	c6 a1	LATIN SMALL LETTER O WITH HORN
        'Ƣ' => 'OI',//	c6 a2	LATIN CAPITAL LETTER OI
        'ƣ' => 'oi',//	c6 a3	LATIN SMALL LETTER OI
        'Ƥ' => 'P',//	c6 a4	LATIN CAPITAL LETTER P WITH HOOK
        'ƥ' => 'p',//	c6 a5	LATIN SMALL LETTER P WITH HOOK
        'Ʀ' => 'YR',//	c6 a6	LATIN LETTER YR
        'ƫ' => 't',//	c6 ab	LATIN SMALL LETTER T WITH PALATAL HOOK
        'Ƭ' => 'T',//	c6 ac	LATIN CAPITAL LETTER T WITH HOOK
        'ƭ' => 't',//	c6 ad	LATIN SMALL LETTER T WITH HOOK
        'Ʈ' => 'T',//	c6 ae	LATIN CAPITAL LETTER T WITH RETROFLEX HOOK
        'Ư' => 'U',//	c6 af	LATIN CAPITAL LETTER U WITH HORN
        'ư' => 'u',//	c6 b0	LATIN SMALL LETTER U WITH HORN
        'Ʊ' => 'U',//	c6 b1	LATIN CAPITAL LETTER UPSILON
        'Ʋ' => 'V',//	c6 b2	LATIN CAPITAL LETTER V WITH HOOK
        'Ƴ' => 'Y',//	c6 b3	LATIN CAPITAL LETTER Y WITH HOOK
        'ƴ' => 'y',//	c6 b4	LATIN SMALL LETTER Y WITH HOOK
        'Ƶ' => 'Z',//	c6 b5	LATIN CAPITAL LETTER Z WITH STROKE
        'ƶ' => 'z',//	c6 b6	LATIN SMALL LETTER Z WITH STROKE
        'Ǎ' => 'A',//	c7 8d	LATIN CAPITAL LETTER A WITH CARON
        'ǎ' => 'a',//	c7 8e	LATIN SMALL LETTER A WITH CARON
        'Ǐ' => 'I',//	c7 8f	LATIN CAPITAL LETTER I WITH CARON
        'ǐ' => 'i',//	c7 90	LATIN SMALL LETTER I WITH CARON
        'Ǒ' => 'O',//	c7 91	LATIN CAPITAL LETTER O WITH CARON
        'ǒ' => 'o',//	c7 92	LATIN SMALL LETTER O WITH CARON
        'Ǔ' => 'U',//	c7 93	LATIN CAPITAL LETTER U WITH CARON
        'ǔ' => 'u',//	c7 94	LATIN SMALL LETTER U WITH CARON
        'Ǖ' => 'U',//	c7 95	LATIN CAPITAL LETTER U WITH DIAERESIS AND MACRON
        'ǖ' => 'u',//	c7 96	LATIN SMALL LETTER U WITH DIAERESIS AND MACRON
        'Ǘ' => 'U',//	c7 97	LATIN CAPITAL LETTER U WITH DIAERESIS AND ACUTE
        'ǘ' => 'u',//	c7 98	LATIN SMALL LETTER U WITH DIAERESIS AND ACUTE
        'Ǚ' => 'U',//	c7 99	LATIN CAPITAL LETTER U WITH DIAERESIS AND CARON
        'ǚ' => 'u',//	c7 9a	LATIN SMALL LETTER U WITH DIAERESIS AND CARON
        'Ǜ' => 'U',//	c7 9b	LATIN CAPITAL LETTER U WITH DIAERESIS AND GRAVE
        'ǜ' => 'u',//	c7 9c	LATIN SMALL LETTER U WITH DIAERESIS AND GRAVE
        'ǝ' => 'e',//	c7 9d	LATIN SMALL LETTER TURNED E
        'Ǟ' => 'A',//	c7 9e	LATIN CAPITAL LETTER A WITH DIAERESIS AND MACRON
        'ǟ' => 'a',//	c7 9f	LATIN SMALL LETTER A WITH DIAERESIS AND MACRON
        'Ǡ' => 'A',//	c7 a0	LATIN CAPITAL LETTER A WITH DOT ABOVE AND MACRON
        'ǡ' => 'a',//	c7 a1	LATIN SMALL LETTER A WITH DOT ABOVE AND MACRON
        'Ǣ' => 'AE',//	c7 a2	LATIN CAPITAL LETTER AE WITH MACRON
        'ǣ' => 'ae',//	c7 a3	LATIN SMALL LETTER AE WITH MACRON
        'Ǥ' => 'G',//	c7 a4	LATIN CAPITAL LETTER G WITH STROKE
        'ǥ' => 'g',//	c7 a5	LATIN SMALL LETTER G WITH STROKE
        'Ǧ' => 'G',//	c7 a6	LATIN CAPITAL LETTER G WITH CARON
        'ǧ' => 'g',//	c7 a7	LATIN SMALL LETTER G WITH CARON
        'Ǩ' => 'K',//	c7 a8	LATIN CAPITAL LETTER K WITH CARON
        'ǩ' => 'k',//	c7 a9	LATIN SMALL LETTER K WITH CARON
        'Ǫ' => 'O',//	c7 aa	LATIN CAPITAL LETTER O WITH OGONEK
        'ǫ' => 'o',//	c7 ab	LATIN SMALL LETTER O WITH OGONEK
        'Ǭ' => 'O',//	c7 ac	LATIN CAPITAL LETTER O WITH OGONEK AND MACRON
        'ǭ' => 'o',//	c7 ad	LATIN SMALL LETTER O WITH OGONEK AND MACRON
        'ǰ' => 'j',//	c7 b0	LATIN SMALL LETTER J WITH CARON
        'Ǳ' => 'DZ',//	c7 b1	LATIN CAPITAL LETTER DZ
        'ǲ' => 'Dz',//	c7 b2	LATIN CAPITAL LETTER D WITH SMALL LETTER Z
        'ǳ' => 'dz',//	c7 b3	LATIN SMALL LETTER DZ
        'Ǵ' => 'G',//	c7 b4	LATIN CAPITAL LETTER G WITH ACUTE
        'ǵ' => 'g',//	c7 b5	LATIN SMALL LETTER G WITH ACUTE
        'Ǹ' => 'N',//	c7 b8	LATIN CAPITAL LETTER N WITH GRAVE
        'ǹ' => 'n',//	c7 b9	LATIN SMALL LETTER N WITH GRAVE
        'Ǻ' => 'A',//	c7 ba	LATIN CAPITAL LETTER A WITH RING ABOVE AND ACUTE
        'ǻ' => 'a',//	c7 bb	LATIN SMALL LETTER A WITH RING ABOVE AND ACUTE
        'Ǽ' => 'AE',//	c7 bc	LATIN CAPITAL LETTER AE WITH ACUTE
        'ǽ' => 'ae',//	c7 bd	LATIN SMALL LETTER AE WITH ACUTE
        'Ǿ' => 'O',//	c7 be	LATIN CAPITAL LETTER O WITH STROKE AND ACUTE
        'ǿ' => 'o',//	c7 bf	LATIN SMALL LETTER O WITH STROKE AND ACUTE
        'Ȁ' => 'A', //	c8 80	LATIN CAPITAL LETTER A WITH DOUBLE GRAVE
        'ȁ' => 'a', //	c8 81	LATIN SMALL LETTER A WITH DOUBLE GRAVE
        'Ȃ' => 'A', //	c8 82	LATIN CAPITAL LETTER A WITH INVERTED BREVE
        'ȃ' => 'a', //	c8 83	LATIN SMALL LETTER A WITH INVERTED BREVE
        'Ȅ' => 'E', //	c8 84	LATIN CAPITAL LETTER E WITH DOUBLE GRAVE
        'ȅ' => 'e', //	c8 85	LATIN SMALL LETTER E WITH DOUBLE GRAVE
        'Ȇ' => 'E', //	c8 86	LATIN CAPITAL LETTER E WITH INVERTED BREVE
        'ȇ' => 'e', //	c8 87	LATIN SMALL LETTER E WITH INVERTED BREVE
        'Ȉ' => 'I', //	c8 88	LATIN CAPITAL LETTER I WITH DOUBLE GRAVE
        'ȉ' => 'i', //	c8 89	LATIN SMALL LETTER I WITH DOUBLE GRAVE
        'Ȋ' => 'I', //	c8 8a	LATIN CAPITAL LETTER I WITH INVERTED BREVE
        'ȋ' => 'i', //	c8 8b	LATIN SMALL LETTER I WITH INVERTED BREVE
        'Ȍ' => 'O', //	c8 8c	LATIN CAPITAL LETTER O WITH DOUBLE GRAVE
        'ȍ' => 'o', //	c8 8d	LATIN SMALL LETTER O WITH DOUBLE GRAVE
        'Ȏ' => 'O', //	c8 8e	LATIN CAPITAL LETTER O WITH INVERTED BREVE
        'ȏ' => 'o', //	c8 8f	LATIN SMALL LETTER O WITH INVERTED BREVE
        'Ȑ' => 'R', //	c8 90	LATIN CAPITAL LETTER R WITH DOUBLE GRAVE
        'ȑ' => 'r', //	c8 91	LATIN SMALL LETTER R WITH DOUBLE GRAVE
        'Ȓ' => 'R', //	c8 92	LATIN CAPITAL LETTER R WITH INVERTED BREVE
        'ȓ' => 'r', //	c8 93	LATIN SMALL LETTER R WITH INVERTED BREVE
        'Ȕ' => 'U', //	c8 94	LATIN CAPITAL LETTER U WITH DOUBLE GRAVE
        'ȕ' => 'u', //	c8 95	LATIN SMALL LETTER U WITH DOUBLE GRAVE
        'Ȗ' => 'U', //	c8 96	LATIN CAPITAL LETTER U WITH INVERTED BREVE
        'ȗ' => 'u', //	c8 97	LATIN SMALL LETTER U WITH INVERTED BREVE
        'Ș' => 'S', //	c8 98	LATIN CAPITAL LETTER S WITH COMMA BELOW
        'ș' => 's', //	c8 99	LATIN SMALL LETTER S WITH COMMA BELOW
        'Ț' => 'T', //	c8 9a	LATIN CAPITAL LETTER T WITH COMMA BELOW
        'ț' => 't', //	c8 9b	LATIN SMALL LETTER T WITH COMMA BELOW
        'Ȟ' => 'H', //	c8 9e	LATIN CAPITAL LETTER H WITH CARON
        'ȟ' => 'h', //	c8 9f	LATIN SMALL LETTER H WITH CARON
        'Ƞ' => 'N', //	c8 a0	LATIN CAPITAL LETTER N WITH LONG RIGHT LEG
        'ȡ' => 'd', //	c8 a1	LATIN SMALL LETTER D WITH CURL
        'Ȣ' => 'OU', //	c8 a2	LATIN CAPITAL LETTER OU
        'ȣ' => 'ou', //	c8 a3	LATIN SMALL LETTER OU
        'Ȥ' => 'Z', //	c8 a4	LATIN CAPITAL LETTER Z WITH HOOK
        'ȥ' => 'z', //	c8 a5	LATIN SMALL LETTER Z WITH HOOK
        'Ȧ' => 'A', //	c8 a6	LATIN CAPITAL LETTER A WITH DOT ABOVE
        'ȧ' => 'a', //	c8 a7	LATIN SMALL LETTER A WITH DOT ABOVE
        'Ȩ' => 'E', //	c8 a8	LATIN CAPITAL LETTER E WITH CEDILLA
        'ȩ' => 'e', //	c8 a9	LATIN SMALL LETTER E WITH CEDILLA
        'Ȫ' => 'O', //	c8 aa	LATIN CAPITAL LETTER O WITH DIAERESIS AND MACRON
        'ȫ' => 'o', //	c8 ab	LATIN SMALL LETTER O WITH DIAERESIS AND MACRON
        'Ȭ' => 'O', //	c8 ac	LATIN CAPITAL LETTER O WITH TILDE AND MACRON
        'ȭ' => 'o', //	c8 ad	LATIN SMALL LETTER O WITH TILDE AND MACRON
        'Ȯ' => 'O', //	c8 ae	LATIN CAPITAL LETTER O WITH DOT ABOVE
        'ȯ' => 'o', //	c8 af	LATIN SMALL LETTER O WITH DOT ABOVE
        'Ȱ' => 'O', //	c8 b0	LATIN CAPITAL LETTER O WITH DOT ABOVE AND MACRON
        'ȱ' => 'O', //	c8 b1	LATIN SMALL LETTER O WITH DOT ABOVE AND MACRON
        'Ȳ' => 'Y', //	c8 b2	LATIN CAPITAL LETTER Y WITH MACRON
        'ȳ' => 'y', //	c8 b3	LATIN SMALL LETTER Y WITH MACRON
        'ȴ' => 'l', //	c8 b4	LATIN SMALL LETTER L WITH CURL
        'ȵ' => 'n', //	c8 b5	LATIN SMALL LETTER N WITH CURL
        'ȶ' => 't', //	c8 b6	LATIN SMALL LETTER T WITH CURL
        'ȷ' => 'j', //	c8 b7	LATIN SMALL LETTER DOTLESS J
        'Ⱥ' => 'A', //	c8 ba	LATIN CAPITAL LETTER A WITH STROKE
        'Ȼ' => 'C', //	c8 bb	LATIN CAPITAL LETTER C WITH STROKE
        'ȼ' => 'c', //	c8 bc	LATIN SMALL LETTER C WITH STROKE
        'Ƚ' => 'L', //	c8 bd	LATIN CAPITAL LETTER L WITH BAR
        'Ⱦ' => 'T', //	c8 be	LATIN CAPITAL LETTER T WITH DIAGONAL STROKE
        'ȿ' => 's', //	c8 bf	LATIN SMALL LETTER S WITH SWASH TAIL
        'ɀ' => 'z', //	c9 80	LATIN SMALL LETTER Z WITH SWASH TAIL
        'Ƀ' => 'B', //	c9 83	LATIN CAPITAL LETTER B WITH STROKE
        'Ʉ' => 'U', //	c9 84	LATIN CAPITAL LETTER U BAR
        'Ʌ' => 'V', //	c9 85	LATIN CAPITAL LETTER TURNED V
        'Ɇ' => 'E', //	c9 86	LATIN CAPITAL LETTER E WITH STROKE
        'ɇ' => 'e', //	c9 87	LATIN SMALL LETTER E WITH STROKE
        'Ɉ' => 'J', //	c9 88	LATIN CAPITAL LETTER J WITH STROKE
        'ɉ' => 'j', //	c9 89	LATIN SMALL LETTER J WITH STROKE
        'Ɋ' => 'Q', //	c9 8a	LATIN CAPITAL LETTER SMALL Q WITH HOOK TAIL
        'ɋ' => 'q', //	c9 8b	LATIN SMALL LETTER Q WITH HOOK TAIL
        'Ɍ' => 'R', //	c9 8c	LATIN CAPITAL LETTER R WITH STROKE
        'ɍ' => 'r', //	c9 8d	LATIN SMALL LETTER R WITH STROKE
        'Ɏ' => 'Y', //	c9 8e	LATIN CAPITAL LETTER Y WITH STROKE
        'ɏ' => 'y', //	c9 8f	LATIN SMALL LETTER Y WITH STROKE
        'ɐ' => 'a', //	c9 90	LATIN SMALL LETTER TURNED A
        'ɑ' => 'a', //	c9 91	LATIN SMALL LETTER ALPHA
        'ɒ' => 'a', //	c9 92	LATIN SMALL LETTER TURNED ALPHA
        'ɓ' => 'b', //	c9 93	LATIN SMALL LETTER B WITH HOOK
        'ɔ' => 'o', //	c9 94	LATIN SMALL LETTER OPEN O
        'ɕ' => 'c', //	c9 95	LATIN SMALL LETTER C WITH CURL
        'ɖ' => 'd', //	c9 96	LATIN SMALL LETTER D WITH TAIL
        'ɗ' => 'd', //	c9 97	LATIN SMALL LETTER D WITH HOOK
        'ɘ' => 'e', //	c9 98	LATIN SMALL LETTER REVERSED E
        'ɛ' => 'e', //	c9 9b	LATIN SMALL LETTER OPEN E
        'ɜ' => 'e', //	c9 9c	LATIN SMALL LETTER REVERSED OPEN E
        'ɝ' => 'e', //	c9 9d	LATIN SMALL LETTER REVERSED OPEN E WITH HOOK
        'ɞ' => 'e', //	c9 9e	LATIN SMALL LETTER CLOSED REVERSED OPEN E
        'ɟ' => 'j', //	c9 9f	LATIN SMALL LETTER DOTLESS J WITH STROKE
        'ɠ' => 'g', //	c9 a0	LATIN SMALL LETTER G WITH HOOK
        'ɡ' => 'g', //	c9 a1	LATIN SMALL LETTER SCRIPT G
        'ɢ' => 'G', //	c9 a2	LATIN LETTER SMALL CAPITAL G
        'ɥ' => 'h', //	c9 a5	LATIN SMALL LETTER TURNED H
        'ɦ' => 'h', //	c9 a6	LATIN SMALL LETTER H WITH HOOK
        'ɨ' => 'i', //	c9 a8	LATIN SMALL LETTER I WITH STROKE
        'ɪ' => 'I', //	c9 aa	LATIN LETTER SMALL CAPITAL I
        'ɫ' => 'l', //	c9 ab	LATIN SMALL LETTER L WITH MIDDLE TILDE
        'ɬ' => 'l', //	c9 ac	LATIN SMALL LETTER L WITH BELT
        'ɭ' => 'l', //	c9 ad	LATIN SMALL LETTER L WITH RETROFLEX HOOK
        'ɯ' => 'm', //	c9 af	LATIN SMALL LETTER TURNED M
        'ɰ' => 'm', //	c9 b0	LATIN SMALL LETTER TURNED M WITH LONG LEG
        'ɱ' => 'm', //	c9 b1	LATIN SMALL LETTER M WITH HOOK
        'ɲ' => 'n', //	c9 b2	LATIN SMALL LETTER N WITH LEFT HOOK
        'ɳ' => 'n', //	c9 b3	LATIN SMALL LETTER N WITH RETROFLEX HOOK
        'ɴ' => 'N', //	c9 b4	LATIN LETTER SMALL CAPITAL N
        'ɵ' => 'O', //	c9 b5	LATIN SMALL LETTER BARRED O
        'ɶ' => 'OE', //	c9 b6	LATIN LETTER SMALL CAPITAL OE
        'ɹ' => 'r', //	c9 b9	LATIN SMALL LETTER TURNED R
        'ɺ' => 'r', //	c9 ba	LATIN SMALL LETTER TURNED R WITH LONG LEG
        'ɻ' => 'r', //	c9 bb	LATIN SMALL LETTER TURNED R WITH HOOK
        'ɼ' => 'r', //	c9 bc	LATIN SMALL LETTER R WITH LONG LEG
        'ɽ' => 'r', //	c9 bd	LATIN SMALL LETTER R WITH TAIL
        'ɾ' => 'r', //	c9 be	LATIN SMALL LETTER R WITH FISHHOOK
        'ɿ' => 'r', //	c9 bf	LATIN SMALL LETTER REVERSED R WITH FISHHOOK
        'ʀ' => 'R', //	ca 80	LATIN LETTER SMALL CAPITAL R
        'ʁ' => 'R', //	ca 81	LATIN LETTER SMALL CAPITAL INVERTED R
        'ʂ' => 's', //	ca 82	LATIN SMALL LETTER S WITH HOOK
        'ʄ' => 'j', //	ca 84	LATIN SMALL LETTER DOTLESS J WITH STROKE AND HOOK
        'ʇ' => 't', //	ca 87	LATIN SMALL LETTER TURNED T
        'ʈ' => 't', //	ca 88	LATIN SMALL LETTER T WITH RETROFLEX HOOK
        'ʉ' => 'u', //	ca 89	LATIN SMALL LETTER U BAR
        'ʋ' => 'v', //	ca 8b	LATIN SMALL LETTER V WITH HOOK
        'ʌ' => 'v', //	ca 8c	LATIN SMALL LETTER TURNED V
        'ʍ' => 'w', //	ca 8d	LATIN SMALL LETTER TURNED W
        'ʎ' => 'y', //	ca 8e	LATIN SMALL LETTER TURNED Y
        'ʏ' => 'Y', //	ca 8f	LATIN LETTER SMALL CAPITAL Y
        'ʐ' => 'z', //	ca 90	LATIN SMALL LETTER Z WITH RETROFLEX HOOK
        'ʑ' => 'z', //	ca 91	LATIN SMALL LETTER Z WITH CURL
        'ʗ' => 'c', //	ca 97	LATIN LETTER STRETCHED C
        'ʙ' => 'B', //	ca 99	LATIN LETTER SMALL CAPITAL B
        'ʚ' => 'e', //	ca 9a	LATIN SMALL LETTER CLOSED OPEN E
        'ʛ' => 'G', //	ca 9b	LATIN LETTER SMALL CAPITAL G WITH HOOK
        'ʜ' => 'H', //	ca 9c	LATIN LETTER SMALL CAPITAL H
        'ʝ' => 'j', //	ca 9d	LATIN SMALL LETTER J WITH CROSSED-TAIL
        'ʞ' => 'k', //	ca 9e	LATIN SMALL LETTER TURNED K
        'ʟ' => 'l', //	ca 9f	LATIN LETTER SMALL CAPITAL L
        'ʠ' => 'q', //	ca a0	LATIN SMALL LETTER Q WITH HOOK
        'ʮ' => 'h', //	ca ae	LATIN SMALL LETTER TURNED H WITH FISHHOOK
        'ʯ' => 'h', //	ca af	LATIN SMALL LETTER TURNED H WITH FISHHOOK AND TAIL
    ];

    public const NON_PRINTABLE = [
        '–'        => '-',
        '’'        => "'",
        '‘'        => "'",
        '…'        => '...',
        '“'        => '"',
        '”'        => '"',
        "\xc2\x80" => '€',      // "\xe2\x82\xac",      EURO SIGN
        "\xc2\x82" => "'",      // "'",                 SINGLE LOW-9 QUOTATION MARK
        "\xc2\x83" => 'f',      // "\xc6\x92",          LATIN SMALL LETTER F WITH HOOK
        "\xc2\x84" => '"',      // '"',                 DOUBLE LOW-9 QUOTATION MARK
        "\xc2\x85" => '...',    // "\xe2\x80\xa6",      HORIZONTAL ELLIPS
        "\xc2\x86" => '+',      // "\xe2\x80\xa0",      DAGGER
        "\xc2\x87" => '++',     // "\xe2\x80\xa1",      DOUBLE DAGGER
        "\xc2\x88" => "'",      // "'",                 MODIFIER LETTER CIRCUMFLEX ACCENT
        "\xc2\x89" => '%',      // "\xe2\x80\xb0",      PER MILLE SIGN
        "\xc2\x8a" => 'S',      // "\xc5\xa0",          LATIN CAPITAL LETTER S WITH CARON
        "\xc2\x8b" => '<',      // "\xe2\x80\xb9",      SINGLE LEFT-POINTING ANGLE QUOTATION
        "\xc2\x8c" => 'OE',     // "\xc5\x92",          LATIN CAPITAL LIGATURE OE
        "\xc2\x8e" => 'Z',      // "\xc5\xbd",          LATIN CAPITAL LETTER Z WITH CARON
        "\xc2\x91" => "'",      // "\xe2\x80\x98",      LEFT SINGLE QUOTATION MARK
        "\xc2\x92" => "'",      // "'",                 RIGHT SINGLE QUOTATION MARK
        "\xc2\x93" => '"',      // "\xe2\x80\x9c",      LEFT DOUBLE QUOTATION MARK
        "\xc2\x94" => '"',      // "\xe2\x80\x9d",      RIGHT DOUBLE QUOTATION MARK
        "\xc2\x95" => '-',      // "\xe2\x80\xa2",      BULLET
        "\xc2\x96" => '-',      // "\xe2\x80\x93",      EN DASH
        "\xc2\x97" => '-',      // "\xe2\x80\x94",      EM DASH
        "\xc2\x98" => '~',      // "\xcb\x9c",          SMALL TILDE
        "\xc2\x99" => '(TM)',   // "\xe2\x84\xa2",      TRADE MARK SIGN
        "\xc2\x9a" => 's',      // "\xc5\xa1",          LATIN SMALL LETTER S WITH CARON
        "\xc2\x9b" => '>',      // "\xe2\x80\xba",      SINGLE RIGHT-POINTING ANGLE QUOTATION
        "\xc2\x9c" => 'oe',     // "\xc5\x93",          LATIN SMALL LIGATURE OE
        "\xc2\x9e" => 'z',      // "\xc5\xbe",          LATIN SMALL LETTER Z WITH CARON
        "\xc2\x9f" => 'Y',      // "\xc5\xb8",          LATIN CAPITAL LETTER Y WITH DIAERESIS
        "\xc2\xA0" => ' ',      // BBSP
        "\x13"     => '',
        "\x14"     => '',
    ];
}
